# Generated by Django 6.0.7 on 2026-07-29 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subscription'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscription',
            name='subscriptio_followe_905f67_idx',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscribed_to',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='pk',
            field=models.CompositePrimaryKey('subscribed_to_id', 'subscriber_id', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['subscriber'], name='subscriptio_subscri_3cf5ad_idx'),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='following',
        ),
    ]
