# Generated by Django 6.0.7 on 2026-07-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_subscription_subscriptio_followe_905f67_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='notifications',
            field=models.BooleanField(default=True),
        ),
    ]
