# Generated by Django 6.0.8 on 2026-08-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_bio'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['subscribed_to'], name='subscriptio_subscri_070acb_idx'),
        ),
    ]
