# Generated by Django 6.0.7 on 2026-07-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_user_article_author_articlecomments_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articlelikes',
            table='article_likes',
        ),
    ]
