# Generated by Django 6.0.7 on 2026-07-30 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_notifications'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notifications',
            table='notifications',
        ),
    ]
