# Generated by Django 6.0.7 on 2026-07-30 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_notifications_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
