# Generated by Django 6.0.8 on 2026-08-26 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_article_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articleuniqueviews',
            table='article_unique_views',
        ),
        migrations.CreateModel(
            name='ArticleBookmarks',
            fields=[
                ('pk', models.CompositePrimaryKey('article_id', 'user_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='articles.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'article_bookmarks',
            },
        ),
    ]
