# Generated by Django 6.0.8 on 2026-08-30 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_articleuniqueviews_table_articlebookmarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomments',
            old_name='author',
            new_name='user',
        ),
    ]
